title: Iniyan
description: "Programming for fun"
author:
  name: "Iniyan"
  email: "viniyan563@gmail.com"
  url: "https://in1yan.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Iniyan"
year : "2024"
